# Generated by Django 4.0.6 on 2022-07-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduce',
            name='major',
            field=models.CharField(blank=True, default='경영학과', max_length=50, null=True),
        ),
    ]
